### ISSUE TITLE
Accept notes with donations

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma_donations#10]
I'd like to donate to the "Tulsa" operations area of Techlahoma. But https://donate.techlahoma.org/ has no way to tag/annotate/ear-mark my donation for Tulsa.

**Comment by datachomp** [comment]
Earlier this year, the TH board voted to not accept ear-marked donations.  Perhaps it might be time to revisit that.

**Comment by groovecoder** [comment]
Most of the institutional supporters I'm contacting like Tulsa Chamber, Tulsa Community Foundation, and Tulsa Rotary have said they want to make sure their donations go specifically to support Tulsa activities/events/operations. Other entities (OCAST, recruiters, etc.) like the idea of supporting the state-wide stuff.

**Comment by datachomp** [comment]
I think enough real-world scenarios have arisen since the initial discussion to bring it up again.

I think it would be a good idea to get many of these new scenarios in a gist and PR for the board meeting.   cc @DevinClark

**Comment by DevinClark** [comment]
:+1:

**Comment by jagthedrummer** [comment]
This is in staging.
