### ISSUE TITLE
Explain if program/area sponsorship is tax-deductible

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma_donations#17]
First feedback on [the new donations page](http://donate.staging.techlahoma.org/) was, "Are the program & area sponsorships tax deductible?"

**Comment by jagthedrummer** [comment]
@groovecoder Can you help find the answer to this question and write the language you'd like to see on the site? I'm not entirely clear on the answer to this. I kinda think that the answer is "it depends". If they just get some recognition my understanding is that it IS tax-deductible, but that if they get anything else it may only be partially deductible, if at all.

**Comment by groovecoder** [comment]
The answer is indeed "it depends" according to [this article Mike posted in Slack](http://charitylawyerblog.com/2011/05/20/corporate-sponsorship-or-taxable-advertising/).

> Activities that are considered to fall within the safe harbor (tax deductible) include:
> 
>   * an acknowledgment of a sponsor as the exclusive sponsor of an activity of the organization;
> 
>   * use of a sponsor’s logo or slogan (so long as they do not contain qualitative or comparative descriptions of the sponsor’s products, services, facilities or company) in connection with an exempt organization’s activities;
> 
>   * a list of the sponsor’s locations, telephone numbers or Internet addresses, and value-neutral descriptions on the nonprofit’s website or in connection with its activities.
> 
> Taxable Advertising. In contrast, taxable advertising is defined as any message or material (whether broadcast, transmitted, published, displayed, or distributed) that promotes or markets the sponsor’s trade or business or any of its services, facilities, or products. This includes any messages containing:
> 
>   * qualitative or comparative language
> 
>   * price information or other indications of savings or value, or
> 
>   * an endorsement or an inducement to purchase, sell, or use any company, service, facility or product.

So the determining factor seems to be: if we recognize the *sponsor* - it's a safe harbor donation; if we recognize the *sponsor's trade or business or any o fits services, facilities, or products* - it's taxable advertising.

E.g., if we recognize *Mozilla* for sponsoring 200 OK - it's a donation; if we promote *Firefox* for sponsoring 200 OK - it's taxable advertising.

**Comment by groovecoder** [comment]
Is the new staging site running master, or a different branch?

**Comment by jagthedrummer** [comment]
@groovecoder Staging is running on the `jeremy/new-subscriptions` branch.

**Comment by seejessicacode** [comment]
Was this addressed in PR #29? If so, is there anything else we need to do before closing this issue?

**Comment by groovecoder** [comment]
Wasn't address ... i.e., the donate site doesn't say whether program/area sponsorships are tax-deductible. Though it's probably not high priority, as we don't have anyone asking us right now. And we may never have enough people ask us that we need to put it front-and-center on the site.

**Comment by jagthedrummer** [comment]
@groovecoder It sounds like there isn't anything we need to do on this anymore, so I'm going to go ahead and close it. Feel free to re-open it if there's something you'd like to see added.
