### ISSUE TITLE
Early Adopter membership needs to show t-shirt AND polo AND choice of hoodie or mug

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma_donations#22]
[The membership slide](https://docs.google.com/presentation/d/1HxsfjWTCJjBYAhWz3flG3Bd5ChbtOT6GQZaItTG37E8/edit#slide=id.g11964ec562_0_4) says:
Founding Early Adopter - $1,024 / year 
Techlahoma Founding Member T-shirt AND Polo, choice of Hoodie or Yeti Mug
Stratified Website Recognition

[The staging website](http://donate.staging.techlahoma.org/membership) says:
Founding Early Adopter
$1024 / year

Techlahoma Founding Member Hoodie
OR
Techlahoma Founding Member Yeti Mug

Stratified Website Recognition

**Comment by jagthedrummer** [comment]
@groovecoder it's like you read my mind. I was working on this AS you filed this issue. :ghost:

**Comment by jagthedrummer** [comment]
This is fixed on staging.
