### ISSUE TITLE
Update thank you page and receipt

### ISSUE THREAD

**Issue by jagthedrummer** [techlahoma/techlahoma_donations#24]
Remove wording saying that this is a tax receipt. And add : 

"This gift is fully tax deductible and no goods or services were provided to the donor except for a <donor gift> valued at approximately $<XX.XX>.   Exact deductible value of your gift will be provided in your year end receipt."

**Comment by energydev** [comment]
Slightly modified recommended wording.

"This gift is fully tax deductible and no goods or services were provided to the donor except for a valued at approximately $. Exact value of your gift will be provided in your year end receipt."
