### ISSUE TITLE
Change Donations Lander Header Text

### ISSUE THREAD

**Issue by energydev** [techlahoma/techlahoma_donations#27]
"Join in 2016 to be forever recognized as a Founding Member or Sponsor." is the current text. Add somewhere to the page the text "For those interested in receiving donor gifts from the first batch, please, donate by April 30, 2016."

**Comment by jagthedrummer** [comment]
@energydev What do you think about adding this towards the end of the page instead of in the header?

**Comment by energydev** [comment]
@jagthedrummer I'm good with you placing the below text anywhere you find most appropriate on the lander page. "For those interested in receiving donor gifts from the first batch, please, donate by April 30, 2016."
