### ISSUE TITLE
Add Display Name field to be used by Website Recognition

### ISSUE THREAD

**Issue by energydev** [techlahoma/techlahoma_donations#38]
I've already had one member reach out and say their legal name and known name are different, and they would like to be able to enter a legal name for tax receipt purposes and a known name for display on the website.

**Comment by jagthedrummer** [comment]
For simplicity of the user facing form I'm inclined to close this issue and just ask people to reach out to us if they need a different name to appear on their receipt. (I don't _think_ the IRS is actually that big of a stickler on this.)

**Comment by the-simian** [comment]
That's reasonable for now. I would be surprised if there were an overwhelming number of these, but yeah - just have folks contact us, and we'll resolve whatever needs resolving
