### ISSUE TITLE
p tag shows up in Donation thank you email

### ISSUE THREAD

**Issue by piisalie** [techlahoma/techlahoma_donations#44]
```
Your Gift:
  <p>You have elected not to receive a gift.</p>
```
https://github.com/piisalie/techlahoma_donations/blob/master/app/views/donation_mailer/thank_you_email.text.erb#L44
It looks like it's because we're using a text email view, and not HTML.

**Comment by jagthedrummer** [comment]
Thanks, @piisalie!
