### ISSUE TITLE
renew ssl cert

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma_donations#54]
paid for a new cert. here's dnsimples' email to info@techlahoma.org:

> The SSL certificate for donate.techlahoma.org was renewed through DNSimple.
> 
> Your next step is to validate the domain to approve and issue the SSL certificate renewal. Your previous certificate will remain valid until it expires to ease transition to the new certificate.

**Comment by jagthedrummer** [comment]
@amandaharlin Sorry for the confusion on this. We've moved this site to use a Let's Encrypt cert, so we don't need the DNSimple cert anymore. We can just let it expire. (Or maybe we can get them to credit us for it if we never re-issued?)
