### ISSUE TITLE
Test and fix edge cases for various types of card failures

### ISSUE THREAD

**Issue by jagthedrummer** [techlahoma/techlahoma_donations#59]
For both one-time donations and subscriptions we need to run tests with all of the failure mode test card numbers that Stripe provides and make sure that we're handling things appropriately.

https://stripe.com/docs/testing

**Comment by groovecoder** [comment]
Looks like the bad ones are caught and the good ones succeed. The error page might try to provide a little more helpful error message? Can we show the Stripe failure message there?


### 4000000000000010
The address_line1_check and address_zip_check verifications fail. If your account is blocking payments that fail ZIP code validation, the charge is declined.

Donation was successfully created. Thank you!

### 4000000000000028
Charge succeeds but the address_line1_check verification fails.

Donation was successfully created. Thank you!

### 4000000000000036
The address_zip_check verification fails. If your account is blocking payments that fail ZIP code validation, the charge is declined.

Donation was successfully created. Thank you!

### 4000000000000044
Charge succeeds but the address_zip_check and address_line1_check verifications are both unavailable.

Donation was successfully created. Thank you!

### 4000000000000101
If a CVC number is provided, the cvc_check fails. If your account is blocking payments that fail CVC code validation, the charge is declined.

Donation was successfully created. Thank you!

### 4000000000000341
Attaching this card to a Customer object succeeds, but attempts to charge the customer fail.

We're sorry, but something went wrong.

### 4000000000009235
Charge succeeds with a risk_level of elevated and placed into review.

Donation was successfully created. Thank you!

### 4000000000000002
Charge is declined with a card_declined code.

We're sorry, but something went wrong.

### 4100000000000019
Charge is declined with a card_declined code and a fraudulent reason.

We're sorry, but something went wrong.

### 4000000000000127
Charge is declined with an incorrect_cvc code.

We're sorry, but something went wrong.

### 4000000000000069
Charge is declined with an expired_card code.

We're sorry, but something went wrong.

### 4000000000000119
Charge is declined with a processing_error code.

We're sorry, but something went wrong.

### 4242424242424241
Charge is declined with an incorrect_number code as the card number fails the Luhn check.

"Please correct the errors above"

**Comment by jagthedrummer** [comment]
Wow! Thanks for running all these tests, @groovecoder! Much appreciated. I'm working on better error handling today.

**Comment by jagthedrummer** [comment]
Ok, @groovecoder, I just deployed changes to the staging site to handle errors better. We're rescuing `Stripe::CardError`, which is the super-class for all of the errors that you saw above. I don't think we need to re-test all of the problem card numbers, but if you could verify that at least one of them now works that would be great.

**Comment by groovecoder** [comment]
4000000000000341 now shows "
1 error prohibited this donation from being saved:

    Credit card: Your card was declined."

Looks good to me. :shipit:

**Comment by jagthedrummer** [comment]
Thanks for the assist on this @groovecoder! I'm closing this one out.
