### ISSUE TITLE
Thank you page wording

### ISSUE THREAD

**Issue by energydev** [techlahoma/techlahoma_donations#62]
We may want to confirm with someone that the below wording is legit to use on the thank you page. I'm not sure the e-mail we send is the full set of paperwork needing for taxes. The end of year receipts which mention goods and services provided may be what is really needed.

"Your contribution to Techlahoma is tax-deductible. After you donate we'll send you the paperwork to file with your taxes."

**Comment by the-simian** [comment]
The stuff in the email was provided by the CPA specifically for end of year receipts. We can ask about POS verbage too.

**Comment by jagthedrummer** [comment]
This was changed to indicate that tax receipts are sent at the end of the year.
