### ISSUE TITLE
Load unsafe script warning in Chrome

### ISSUE THREAD

**Issue by wassimk** [techlahoma/techlahoma_donations#69]
I can reproduce this by visiting the [donation page](https://donate.techlahoma.org/) in _Chrome 62.0.3202.94 (Official Build) (64-bit)_.

![2017-11-29_08-22-41](https://user-images.githubusercontent.com/2261839/33379855-d7e82f46-d4de-11e7-8690-1208f376ccd4.png)

**Comment by DevinClark** [comment]
Looks like it is either a google font or the newrelic js agent. Should be pretty easy to fix.

**Comment by jagthedrummer** [comment]
Thanks for the report @wassimk, and the assist @DevinClark. Should be all good now.
