### ISSUE TITLE
Receipt Rewrite

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma_donations#7]
After talking to Rob today we thought about rewritting the techlahoma donation email receipt to include more info. This would involve modifying the existing email. (just wanted to put that out there as something I'd like to help with.)

**Comment by rhoegg** [comment]
I'd like to help with this too.  Once we finish getting Xero set up, I
believe it has support for receipt generation.

**Comment by amandaharlin** [comment]
Are you missing any information for the Xero set up? If so we could
chat/call today and get that taken care of. It seems like a good tool and
you've been real keen to contribute this help! :sparkles:

**Comment by jagthedrummer** [comment]
I'm happy to help with the email adjustments. It's just a simple text file, so there's not a lot that can go wrong. 

https://github.com/techlahoma/techlahoma_donations/blob/master/app/views/donation_mailer/thank_you_email.text.erb

**Comment by jagthedrummer** [comment]
(And it is in dire need of a rewrite.)

**Comment by amandaharlin** [comment]
Dude, awesome! In that case I'll just put up a tiny PR and we can review it!

**Comment by amandaharlin** [comment]
:clap: :clap: :clap: :clap: :clap: yessss!

**Comment by the-simian** [comment]
:clap: agree!

**Comment by rhoegg** [comment]
Yep, we need the BOK login information added so that the bank account is
linked.  I haven't checked if Vance added the CC yet either.

**Comment by amandaharlin** [comment]
Awesome, Ryan we can get you that. Jesse called up BOK last week to confirm
log in info, so we've got that and the CC #! Did you want to make the Xero
account since you've already got a subscription? If so, I'll send you
lastpass logins.

**Comment by rhoegg** [comment]
Looks like Xero is actually all set.  I'll take a swipe at making a
donation receipt there, and we'll need to sort out how the online donation
and Xero connect in a separate issue.  Sorry for the hijack!

**Comment by jagthedrummer** [comment]
Is sending the receipt from Xero somehow preferable to sending it directly from the donations app? (Just curious, as it seems like it's just adding more moving parts with more opportunity for something to go wrong and someone to not get their receipt.)

**Comment by rhoegg** [comment]
Well it allows us to send receipts for donations we get other ways (check,
in kind)

**Comment by jagthedrummer** [comment]
Ah-ha!

**Comment by amandaharlin** [comment]
If we do set up Xero to send out the tax receipt this repo could still send out the 'thank you' email. What do y'all think, is that ok with everyone? (The class we took said both were good to do.)

**Comment by jagthedrummer** [comment]
@amandaharlin @rhoegg Has there been any resolution on this? I think the site is still sending a receipt. Are we also sending one through another channel? If not we should probably just rewrite the one in the app.

**Comment by jagthedrummer** [comment]
We need to include instructions about ordering additional items and something saying that you can just rely to the email with questions.

**Comment by jagthedrummer** [comment]
@amandaharlin @rhoegg Pinging on again on this.

Already in this thread there are 2 issues:

1) What should the receipt say?
2) Where should it be sent from?

And if the answer to the second question is "somewhere other than from the donations site", then we also have the question of:

3) How do we get info from the donations site to wherever/whatever/whoever will be sending the receipt?

**Comment by rhoegg** [comment]
Looking back at the comments, I might have overcomplicated this :)  Let's send an immediate receipt from the donations site. We should also make sure other forms of payment receive one quickly, but through plain email or postal mail.

If we decide to do some annual thank you letters, those should be the same for all donors, regardless of the method of payment. But, those should be done in a separate issue too. :)

Here's some [guidelines](https://www.councilofnonprofits.org/tools-resources/saying-thank-you-to-donors) on what should be in the receipt.

**Comment by jagthedrummer** [comment]
I took a stab at rewriting this. You can check it out on staging: http://donate.staging.techlahoma.org/
