### ISSUE TITLE
2017 Tax Receipts

### ISSUE THREAD

**Issue by vlucas** [techlahoma/techlahoma_donations#74]
We need to send all the end of year tax receipts. I will work on the wording and update this issue accordingly.

**Comment by vlucas** [comment]
Text from last year (2016 tax year):

```
I wanted to say thanks so much for giving generously to Techlahoma in 2016 (and 2015). Your donation made it possible to teach 2 classes of women beginning front-end skills (that's 40 women whose lives were impacted!), support 24 user groups, and provide over 240 hours of free stem education in OKC and Tulsa throughout 2016. 

Your gift made a major impact in the OKC tech community by allowing us to rent and outfit an event center. Our streaming setup allows us to reach rural Oklahomans, students, and other aspiring professionals who are unable to attend meetings but still have the drive to learn online. Having this meeting location and A/V streaming resource made Oklahoma's tech community more stable, sustainable, and successful thanks to your plank donation and member donation. 

We're an all-volunteer team (as you know - you're our co-founder) so your money went straight to the community to make a difference in people's lives through programs like code club, okcjs, and many more tech events that are helping make Oklahoma an up-and-coming tech hub. 

If you need anything, please let me know!

Sincerely,

Amanda Harlin
Treasurer
```

**Comment by vlucas** [comment]
Wording in the PDF document:

> Techlahoma Foundation
> Receipt of charitable giving

> Techlahoma acknowledges and expresses appreciation for the following donation:
> Donation #1
> Date of Donation: 03/10/2016
> Donation received from: Vance Lucas
> Cash donation in the amount of: $XXX
> Electronic Signature of authorized representative: Amanda Harlin, Treasurer
> Goods Received
> Value of goods provided by Techlahoma: T-Shirt $12, Hoodie: $35.60
> Your charitable deduction for federal income tax purposes is limited to the excess of the
> amount of money contributed over the value of the goods or services provided by the
> charity.
> 
> Techlahoma Foundation
> Receipt of charitable giving
> Techlahoma acknowledges and expresses appreciation for the following donation:
> Donation #2
> Date of Donation: 07/25/2016
> Donation received from: Vance Lucas
> Cash donation in the amount of: $XXX
> Electronic Signature of authorized representative: Amanda Harlin, Treasurer
> Goods Received
> No goods or services were received for this donation.
> 
> About the Techlahoma Foundation
> The Techlahoma Foundation, otherwise known as Techlahoma, is a federally recognized
> 501 (c) (3) registered non-profit organization; Federal ID Number 46-5519987.

**Comment by jagthedrummer** [comment]
@vlucas Do you want to make changes to any of this wording?

**Comment by jagthedrummer** [comment]
I think we'll need to make at least a few changes. The email body portion seems to have been written specifically for you. We also should update the numbers on groups and classes taught and what not.

**Comment by vlucas** [comment]
For 2017, we can add a paragraph above the tax receipt email:

> Thank you for your generous gift to support the Techlahoma Foundation. In 2017, your gift helped support 35 user groups, 2 national conferences, and provide over 400 hours of free STEM education in Oklahoma throughout 2017. And since Techlahoma is all volunteer run, 100% of your money went directly towards supporting and growing the local tech community. We have had a great year, and we hope for your continued support in 2018 and beyond.

**Comment by vlucas** [comment]
We sent these out. Closing this :)
