### ISSUE TITLE
Server's certificate has expired

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma_donations#8]
we purchased a new cert last month since the older one expired

**Comment by jagthedrummer** [comment]
If someone can let me know where to get that (or get me the new cert and key) I can get them installed.

**Comment by amandaharlin** [comment]
Thank you! Sending you the lastpass login!

**Comment by jagthedrummer** [comment]
Can you hit me at my octolabs.com address, please? (jeremy@...) Thanks!

**Comment by amandaharlin** [comment]
(Thanks for specifying! Good to know preferred email :thumbsup:) Just
unshared and reshared, maybe it'll hit your email now?

**Comment by amandaharlin** [comment]
Thank yoouuuu!

**Comment by jagthedrummer** [comment]
Ok, got the cert, but heroku isn't wanting to take the update. I've opened a support ticket with them.

**Comment by datachomp** [comment]
I already updated it.   Is heroku confused by trying to update a cert with the same cert?

**Comment by the-simian** [comment]
YES! glad this got knocked out!
