### ISSUE TITLE
Increase max donation

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma_donations#9]
I got a windfall gain that I want to donate to Techlahoma. I can't do it via https://donate.techlahoma.org/ because the donation amount caps at $500.

**Comment by datachomp** [comment]
cc @jagthedrummer

**Comment by jagthedrummer** [comment]
I just upped the max donation to $5k. Let me know if that's not enough. :smile: :heart:

**Comment by the-simian** [comment]
Thank you!
